# Generated by Django 2.1.5 on 2019-01-30 15:38

import cvat.apps.engine.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_task_segment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_files',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=cvat.apps.engine.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='task',
            name='remote_files',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='server_files',
            field=models.TextField(blank=True),
        ),
    ]
