# Generated by Django 2.1.5 on 2019-01-31 09:13

import cvat.apps.engine.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20190130_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage, upload_to=cvat.apps.engine.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ANNOTATION', 'annotation'), ('VALIDATION', 'validation'), ('COMPLETED', 'completed')], default=cvat.apps.engine.models.StatusChoice('annotation'), max_length=32),
        ),
    ]
