# Generated by Django 2.1.5 on 2019-01-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20190131_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
    ]
