# Generated by Django 2.1.5 on 2019-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_remove_task_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_quality',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
