# Generated by Django 2.1.5 on 2019-02-05 21:25

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_auto_20190205_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(storage=cvat.apps.engine.models.MyFileSystemStorage(), upload_to=cvat.apps.engine.models.upload_path_handler),
        ),
        migrations.AlterUniqueTogether(
            name='clientfile',
            unique_together={('task', 'file')},
        ),
    ]
